/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createServerCustomersEndPointsCustomersCreateCreateCustomersResponseFromDiscriminatorValue, serializeServerCustomersEndPointsCustomersCreateCreateCustomersRequest, serializeServerCustomersEndPointsCustomersCreateCreateCustomersResponse, type ServerCustomersEndPointsCustomersCreateCreateCustomersRequest, type ServerCustomersEndPointsCustomersCreateCreateCustomersResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customers
 */
export interface CustomersRequestBuilder extends BaseRequestBuilder<CustomersRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerCustomersEndPointsCustomersCreateCreateCustomersResponse>}
     */
     post(body: ServerCustomersEndPointsCustomersCreateCreateCustomersRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerCustomersEndPointsCustomersCreateCreateCustomersResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ServerCustomersEndPointsCustomersCreateCreateCustomersRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CustomersRequestBuilderUriTemplate = "{+baseurl}/customers";
/**
 * Metadata for all the requests in the request builder.
 */
export const CustomersRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CustomersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createServerCustomersEndPointsCustomersCreateCreateCustomersResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServerCustomersEndPointsCustomersCreateCreateCustomersRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
