/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createServerLoanEndPointsLoanUpdateLoanStatusUpdateLoanStatuResponseFromDiscriminatorValue, type ServerLoanEndPointsLoanUpdateLoanStatusUpdateLoanStatuResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /loan/update-status/{loanId}/{status}
 */
export interface WithStatusItemRequestBuilder extends BaseRequestBuilder<WithStatusItemRequestBuilder> {
    /**
     * Update status of a loan
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerLoanEndPointsLoanUpdateLoanStatusUpdateLoanStatuResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerLoanEndPointsLoanUpdateLoanStatusUpdateLoanStatuResponse | undefined>;
    /**
     * Update status of a loan
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithStatusItemRequestBuilderUriTemplate = "{+baseurl}/loan/update-status/{loanId}/{status}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithStatusItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithStatusItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createServerLoanEndPointsLoanUpdateLoanStatusUpdateLoanStatuResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
