/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithLoanItemRequestBuilder, WithLoanItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /loan/update-status
 */
export interface UpdateStatusRequestBuilder extends BaseRequestBuilder<UpdateStatusRequestBuilder> {
    /**
     * Gets an item from the MyCompanyName.loan.updateStatus.item collection
     * @param loanId Unique identifier of the item
     * @returns {WithLoanItemRequestBuilder}
     */
     byLoanId(loanId: string) : WithLoanItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UpdateStatusRequestBuilderUriTemplate = "{+baseurl}/loan/update-status";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UpdateStatusRequestBuilderNavigationMetadata: Record<Exclude<keyof UpdateStatusRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLoanId: {
        navigationMetadata: WithLoanItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["loanId"],
    },
};
/* tslint:enable */
/* eslint-enable */
