/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createServerLoanEndPointsLoanGetLoansGetLoansResponseFromDiscriminatorValue, type ServerLoanEndPointsLoanGetLoansGetLoansResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /loan
 */
export interface LoanRequestBuilder extends BaseRequestBuilder<LoanRequestBuilder> {
    /**
     * Get all loans
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerLoanEndPointsLoanGetLoansGetLoansResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerLoanEndPointsLoanGetLoansGetLoansResponse | undefined>;
    /**
     * Get all loans
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LoanRequestBuilderUriTemplate = "{+baseurl}/loan";
/**
 * Metadata for all the requests in the request builder.
 */
export const LoanRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LoanRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createServerLoanEndPointsLoanGetLoansGetLoansResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
