/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createServerLoanEndPointsLoanSubmitSubmitLoanResponseFromDiscriminatorValue, serializeServerLoanEndPointsLoanSubmitSubmitLoanRequest, serializeServerLoanEndPointsLoanSubmitSubmitLoanResponse, type ServerLoanEndPointsLoanSubmitSubmitLoanRequest, type ServerLoanEndPointsLoanSubmitSubmitLoanResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /loan
 */
export interface LoanRequestBuilder extends BaseRequestBuilder<LoanRequestBuilder> {
    /**
     * Submit a loan application to the system
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerLoanEndPointsLoanSubmitSubmitLoanResponse>}
     */
     post(body: ServerLoanEndPointsLoanSubmitSubmitLoanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerLoanEndPointsLoanSubmitSubmitLoanResponse | undefined>;
    /**
     * Submit a loan application to the system
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ServerLoanEndPointsLoanSubmitSubmitLoanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LoanRequestBuilderUriTemplate = "{+baseurl}/loan";
/**
 * Metadata for all the requests in the request builder.
 */
export const LoanRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LoanRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createServerLoanEndPointsLoanSubmitSubmitLoanResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServerLoanEndPointsLoanSubmitSubmitLoanRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
