/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithStatusItemRequestBuilder, WithStatusItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /loan/update-status/{loanId}
 */
export interface WithLoanItemRequestBuilder extends BaseRequestBuilder<WithLoanItemRequestBuilder> {
    /**
     * Gets an item from the MyCompanyName.loan.updateStatus.item.item collection
     * @param status Unique identifier of the item
     * @returns {WithStatusItemRequestBuilder}
     */
     byStatus(status: string) : WithStatusItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithLoanItemRequestBuilderUriTemplate = "{+baseurl}/loan/update-status/{loanId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithLoanItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithLoanItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byStatus: {
        requestsMetadata: WithStatusItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["status"],
    },
};
/* tslint:enable */
/* eslint-enable */
